repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        # --select I sorts imports
        args: [ --fix, --extend-select, I  ]
      # Run the formatter.
      - id: ruff-format
